name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ensure directory exists and clean up
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@eazycourt.com "mkdir -p /home/ec2-user/easycourt && rm -rf /home/ec2-user/easycourt/*"

    - name: Transfer files to Lightsail
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@eazycourt.com:/home/ec2-user/easycourt/

    - name: Deploy on Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@eazycourt.com << 'EOF'
          cd /home/ec2-user/easycourt
          /usr/local/go/bin/go build -o server cmd/main.go
          pm2 stop server || true
          pm2 start ./server --name server
          pm2 save
        EOF
