name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@eazycourt.com << 'EOF'
          cd /home/ec2-user
          if [ -d "easycourt" ]; then
            cd your-repo-name && git pull
          else
            git clone https://github.com/minacio00/easycourt.git && cd easycourt
          fi
          go build -o server cmd/main.go
          pm2 stop server || true
          pm2 start ./server --name server
          pm2 save
        EOF
