name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Use the Go version you're targeting

    - name: Build the Go project
      run: |
        go build -o server cmd/main.go  # Build the project into a binary named 'server'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}  # Using your correct SSH key

    - name: Ensure directory exists and clean up
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@eazycourt.com "mkdir -p /home/ec2-user/easycourt && rm -rf /home/ec2-user/easycourt/*"

    - name: Transfer binary and other necessary files to Lightsail
      run: |
        scp -o StrictHostKeyChecking=no server ec2-user@eazycourt.com:/home/ec2-user/easycourt/
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@eazycourt.com:/home/ec2-user/easycourt/

    - name: Deploy on Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@eazycourt.com << 'EOF'
          cd /home/ec2-user/easycourt
          pm2 stop server || true
          pm2 start ./server --name server
          pm2 save
        EOF
